sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$APP_NAME:latest .
  - docker run -d -p 6060:6060 -e PORT=$PORT --name hsh_test $DOCKER_USERNAME/$APP_NAME

script:
  - echo 1
  # - docker exec hsh_test npm run test

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master