version: '3'
services:
  app:
    image: hholzmann16/hsh
    container_name: HSH_app
    build:
      context: .
    command: ./start.sh
    ports:
      - 6060:6060 # must match PORT env var
    environment:
      - PORT=6060
      - DB_NAME=hsh_db
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_PORT=3306
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db_data:
